spring:
  profiles:
    active: dev
    

---
server:
  port: 8083
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8084
spring:
  profiles: test
  application:
    name: springcloud-config-test
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
